inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - Guardfile
    - grape-active_model_serializers.gemspec
  NewCops: enable

Style/BlockDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
